local NoobTacoUI, E, L, V, P, G = unpack(select(2, ...))

function NoobTacoUI:UnitframeRaid1()
    E.db["unitframe"]["units"]["raid"]["buffIndicator"]["enable"] = true
    E.db["unitframe"]["units"]["raid"]["buffIndicator"]["size"] = 10
    E.db["unitframe"]["units"]["raid"]["buffs"]["perrow"] = 8
    E.db["unitframe"]["units"]["raid"]["debuffs"]["anchorPoint"] = "TOP"
    E.db["unitframe"]["units"]["raid"]["debuffs"]["attachTo"] = "FRAME"
    E.db["unitframe"]["units"]["raid"]["debuffs"]["clickThrough"] = true
    E.db["unitframe"]["units"]["raid"]["debuffs"]["countFont"] = "Exo2-Bold"
    E.db["unitframe"]["units"]["raid"]["debuffs"]["enable"] = true
    E.db["unitframe"]["units"]["raid"]["debuffs"]["numrows"] = 2
    E.db["unitframe"]["units"]["raid"]["debuffs"]["perrow"] = 3
    E.db["unitframe"]["units"]["raid"]["debuffs"]["sizeOverride"] = 18
    E.db["unitframe"]["units"]["raid"]["debuffs"]["xOffset"] = 0
    E.db["unitframe"]["units"]["raid"]["debuffs"]["yOffset"] = -40
    E.db["unitframe"]["units"]["raid"]["growthDirection"] = "RIGHT_UP"
    E.db["unitframe"]["units"]["raid"]["healPrediction"]["enable"] = true
    E.db["unitframe"]["units"]["raid"]["health"]["position"] = "CENTER"
    E.db["unitframe"]["units"]["raid"]["health"]["text_format"] = "[health:current-percent]"
    E.db["unitframe"]["units"]["raid"]["health"]["xOffset"] = 0
    E.db["unitframe"]["units"]["raid"]["health"]["yOffset"] = -10
    E.db["unitframe"]["units"]["raid"]["height"] = 45
    E.db["unitframe"]["units"]["raid"]["infoPanel"]["enable"] = false
    E.db["unitframe"]["units"]["raid"]["name"]["attachTextTo"] = "Frame"
    E.db["unitframe"]["units"]["raid"]["name"]["position"] = "CENTER"
    E.db["unitframe"]["units"]["raid"]["name"]["text_format"] = "[name:veryshort] [difficultycolor][smartlevel]"
    E.db["unitframe"]["units"]["raid"]["name"]["yOffset"] = 10
    E.db["unitframe"]["units"]["raid"]["numGroups"] = 5
    E.db["unitframe"]["units"]["raid"]["power"]["height"] = 10
    E.db["unitframe"]["units"]["raid"]["power"]["position"] = "RIGHT"
    E.db["unitframe"]["units"]["raid"]["power"]["yOffset"] = 0
    E.db["unitframe"]["units"]["raid"]["raidRoleIcons"]["yOffset"] = -2
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["font"] = "Exo2-Bold"
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["size"] = 20
    E.db["unitframe"]["units"]["raid"]["rdebuffs"]["yOffset"] = 5
    E.db["unitframe"]["units"]["raid"]["readycheckIcon"]["position"] = "TOPRIGHT"
    E.db["unitframe"]["units"]["raid"]["readycheckIcon"]["size"] = 30
    E.db["unitframe"]["units"]["raid"]["readycheckIcon"]["yOffset"] = 0
    E.db["unitframe"]["units"]["raid"]["resurrectIcon"]["attachTo"] = "BOTTOMRIGHT"
    E.db["unitframe"]["units"]["raid"]["resurrectIcon"]["size"] = 40
    E.db["unitframe"]["units"]["raid"]["roleIcon"]["combatHide"] = true
    E.db["unitframe"]["units"]["raid"]["roleIcon"]["damager"] = false
    E.db["unitframe"]["units"]["raid"]["roleIcon"]["size"] = 12
    E.db["unitframe"]["units"]["raid"]["verticalSpacing"] = -1
    E.db["unitframe"]["units"]["raid"]["verticalSpacing"] = 2
    E.db["unitframe"]["units"]["raid"]["visibility"] = "[@raid6,noexists][@raid26,exists] hide;show"
    E.db["unitframe"]["units"]["raid"]["width"] = 90
end
